#!/bin/bash

#SBATCH -A AST182          # Project/Allocation name (req'd if you have more than 1)
#SBATCH -t 00:10:00        # Run time (hh:mm:ss)
#SBATCH -p batch           # Queue (partition) name
#SBATCH -c 7
#SBATCH --tasks-per-node=8
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=closest

source ${ETKGUIDE}/amd/Load-Module-CarpetX.sh

module list

export MPICH_GPU_IPC_CACHE_MAX_SIZE=1000  # for cray-mpich/8.1.30
#export GTL_HSA_MAX_IPC_CACHE_SIZE=1000  # for cray-mpich/8.1.28 or cray-mpich/8.1.29

# ------------------------------------------------------
# Create a directory for the current run and launch jobs
# ------------------------------------------------------
create_and_organize_job_directory_and_launch_jobs "${SUBMITJOBS_PARFILE}" "${SUBMITJOBS_JOBNAME}" "${SLURM_JOB_ID}"
