#!/bin/bash
#PBS -r n
#PBS -q short
#PBS -l walltime=00:30:00
#PBS -l select=2:ncpus=32:mpiprocs=32:ompthreads=1
#PBS -N readcalc
##PBS -M your@email
##PBS -m bae

cd $PBS_O_WORKDIR

# Load required environment
. ~spack/newspack/share/spack/setup-env.sh
spack env activate etk_gcc_13

# Environment setup
export IPATH_NO_CPUAFFINITY=1
export OMP_NUM_THREADS=1

# Log job ID for reference
echo ${PBS_JOBID} > .jobid

# ------------------------------------------------------
# Create a directory for the current run and launch jobs
# ------------------------------------------------------
create_and_organize_job_directory_and_launch_jobs "${SUBMITJOBS_PARFILE}" "${SUBMITJOBS_JOBNAME}" "${PBS_JOBID}"
