#!/bin/bash

##SBATCH --mail-type=all    # Send email at begin and end of job
##SBATCH --mail-user=ljsma@rit.edu

module list

# ------------------------------------------------------
# Create a directory for the current run and launch jobs
# ------------------------------------------------------
create_and_organize_job_directory_and_launch_jobs "${SUBMITJOBS_PARFILE}" "${SUBMITJOBS_JOBNAME}" "${SLURM_JOB_ID}"
