#!/bin/bash

module reset
module load gcc-native/12.3
module load cuda/12.9
module load craype-accel-nvidia80
module load cray-hdf5-parallel/1.14.3.7
module load cray-fftw/3.3.10.11

export MPICH_GPU_SUPPORT_ENABLED=1
export ETKPATH="${ETKPATH:-/home/jkalinan/EinsteinToolkit}"
export PATH="${ETKPATH}/cmake/bin:${PATH}"
