#!/bin/bash

module reset

module unload openmpi
module unload nvidia

module load gcc/14.2.0
module load cuda/12.8
module load nvmath
module load nvpl
module load openmpi
module load boost
module load fftw3
module load gsl
module load zlib
#module load phdf5
module load silo

#module load adios2  # not compatible with gcc13
#module load silo    # not compatible with phdf5
