[deltaai]

# last-tested-on: 2026-03-04
# last-tested-by: Cheng-Hsin Cheng <chcheng3@illinois.edu>
# last-reviewed-on: 2026-07-29
# last-reviewed-by: Jay Kalinani

# Machine description
nickname        = deltaai
name            = DeltaAI
location        = NCSA
description     = NCSA DeltaAI GH200 GPU cluster
webpage         = https://docs.ncsa.illinois.edu/systems/deltaai/
status          = production

# Access to this machine
hostname        = dtai-login.delta.ncsa.illinois.edu
envsetup        = <<EOT
module reset &&
module load craype-accel-nvidia90 &&
module load gcc-native/14 &&
module load cray-mpich/9.0.1 &&
module load cudatoolkit/25.5_12.9 &&
module load cray-hdf5-parallel &&
module load cmake/3.30.2 &&
module load openblas &&
module load gsl &&
module load cray-fftw &&
export MPICH_GPU_SUPPORT_ENABLED=1
EOT

aliaspattern    = ^gh-login[0-9][0-9]?\.delta\.ncsa\.illinois\.edu$

sourcebasedir   = /work/hdd/@("@ALLOCATION@"[0:4])@/@USER@/EinsteinToolkit
disabled-thorns = <<EOT
EOT
enabled-thorns = <<EOT
EOT
optionlist      = deltaai.cfg
submitscript    = deltaai.sub
runscript       = deltaai.run
makejobs        = 18
make            = make -j@MAKEJOBS@

# Four GH200 superchips and 288 Grace CPU cores per node. Using 72 cores per
# process gives four MPI ranks per node and one rank per GPU.
basedir         = /work/hdd/@("@ALLOCATION@"[0:4])@/@USER@/simulations
cpu             = NVIDIA Grace
cpufreq         = 3.35
flop/cycle      = 16
ppn             = 288
spn             = 4
mpn             = 4
max-num-smt     = 1
num-smt         = 1
max-num-threads = 288
num-threads     = 72
memory          = 488000
nodes           = 150
min-ppn         = 288
allocation      = NO_ALLOCATION
queue           = ghx4
maxwalltime     = 48:00:00
maxqueueslots   = 150
submit          = sbatch @SCRIPTFILE@; sleep 5
getstatus       = squeue -j @JOB_ID@
stop            = scancel @JOB_ID@
submitpattern   = Submitted batch job ([0-9]+)
statuspattern   = '@JOB_ID@ '
queuedpattern   = ' PD '
runningpattern  = ' (CF|CG|R|TO) '
holdingpattern  = '\(JobHeldUser\)'
exechost        = hostname
exechostpattern = ^(\S+)
stdout          = cat @SIMULATION_NAME@.out
stderr          = cat @SIMULATION_NAME@.err
stdout-follow   = tail -n 100 -f @SIMULATION_NAME@.out @SIMULATION_NAME@.err
