#!/bin/bash
set -euo pipefail
cd @RUNDIR@-active
export SIMULATION_ID='@SIMULATION_ID@'
export CACTUS_MAX_MEMORY='@(@MEMORY@ * 1024)@'
export CACTUS_NUM_PROCS='@NUM_PROCS@'
export CACTUS_NUM_THREADS='@NUM_THREADS@'
export CUDA_DEVICE_ORDER=PCI_BUS_ID
export MPICH_GPU_SUPPORT_ENABLED=1
export OMP_NUM_THREADS='@NUM_THREADS@'
export OMP_PLACES=cores
export OMP_PROC_BIND=spread
mkdir -p SIMFACTORY
env | sort > SIMFACTORY/ENVIRONMENT
printf '%s\n' "${PBS_NODEFILE:-unknown}" > SIMFACTORY/NODES
mpiexec -n @NUM_PROCS@ --ppn @NODE_PROCS@ --cpu-bind depth -d @NUM_THREADS@ "@EXECUTABLE@" -L 3 "@PARFILE@"
