#!/bin/bash

###############################################################################
# basic
###############################################################################
module reset

module unload darshan-runtime

module load PrgEnv-cray
module load cpe/25.09
module load cray-mpich/9.0.1
module load craype-accel-amd-gfx90a
module load rocm/6.4.2
module load hipfort/6.4.2

###############################################################################
# more for carpetx
###############################################################################
module load cray-fftw
module load cray-hdf5-parallel/1.14.3.7
# NOTE: make sure the available openpmd-api/adios2 module variants are
# compatible with the cpe/25.09 + cray-mpich/9.0.1 stack
# (check with `module spider openpmd-api` and `module spider adios2`)
module load openpmd-api
module load boost
module load hwloc
module load adios2
module load libjpeg-turbo
module load openblas
module load zlib
module load gsl

###############################################################################
# set more env variables
###############################################################################
export LD_LIBRARY_PATH=${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}

export MPICH_GPU_SUPPORT_ENABLED=1
export MPICH_VERSION_DISPLAY=1  # confirm the runtime uses the intended cray-mpich version
export PE_MPICH_GTL_DIR_amd_gfx90a="-L/opt/cray/pe/mpich/9.0.1/gtl/lib"
export PE_MPICH_GTL_LIBS_amd_gfx90a="-lmpi_gtl_hsa"

###############################################################################
# workaround for gpu-aware-mpi
###############################################################################
# Needed for cray-mpich/8.1.30; untested with cray-mpich/9.0.1 -- remove if
# GPU-aware MPI works without it on the new stack
export MPICH_GPU_IPC_CACHE_MAX_SIZE=1000
#export GTL_HSA_MAX_IPC_CACHE_SIZE=1000  # for cray-mpich/8.1.28 or cray-mpich/8.1.29

