#!/bin/bash

module purge
module reset

module load nvidia_math
module load nvpl
module load phdf5
module load boost
module load fftw3
module load gsl
module load zlib
module load adios2
#module load cuda

#module load silo
