#!/bin/bash

module reset

module load nvidia/24.9
module load nvpl
module load phdf5
module load boost
module load fftw3
module load gsl
module load zlib
module load adios2
#module load cuda
#module load nvidia_math

#module load silo
