#!/bin/bash

exe() { echo "\$ $@" ; "$@" ; }
#exe() { echo "\$ $@" ; }

echo "Compile (c) 2022 Liwei Ji"

exename="AsterX"
thornlist="thornlists/asterx-frontier.th"
config="$HOME/Tools/ETK-Compile-Guides/frontier/configs/frontier-amd.cfg"
compile_fresh=0

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "usage: Compile [exe thornlist config] [fresh]"
  echo "defaults:"
  echo "  exe       = $exename"
  echo "  thornlist = $thornlist"
  echo "  config    = $config"
  exit 0
fi

if [ ! -z "$1" ] && [ "${@: -1}" == "fresh" ]; then
  compile_fresh=1
fi
if [ ! -z "$1" ] && [ "$1" != "fresh" ]; then
  exename=$1
fi
if [ ! -z "$2" ] && [ "$2" != "fresh" ]; then
  thornlist=$2
fi
if [ ! -z "$3" ] && [ "$3" != "fresh" ]; then
  config=$3
fi

exe source $HOME/Tools/ETK-Compile-Guides/frontier/Load-Module-CarpetX-cce15-rocm6.0-amd.sh
exe ml
echo "MPICH_GPU_SUPPORT_ENABLED    = $MPICH_GPU_SUPPORT_ENABLED"
echo "PE_MPICH_GTL_DIR_amd_gfx90a  = $PE_MPICH_GTL_DIR_amd_gfx90a"
echo "PE_MPICH_GTL_LIBS_amd_gfx90a = $PE_MPICH_GTL_LIBS_amd_gfx90a"

#exe cd $CACTUSX
if [ $compile_fresh == 1 ]; then
  exe gmake $exename options=$config
  exe cp $thornlist configs/$exename/ThornList
fi
exe gmake -j24 $exename
